localStorage.removeItem("reservation")
localStorage.removeItem("vehicle")
localStorage.removeItem("client")
localStorage.removeItem("maintenance")
localStorage.removeItem("unavailability")
localStorage.removeItem("bookVehicle")